---
name: pre-commit

# Controls when the workflow will run
on:
  pull_request:
    paths:
      - '.github/workflows/pre-commit.yml'
      - '.pre-commit-config.yaml'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v3

      - name: Lint the repository with pre-commit
        uses: pre-commit/action@v3.0.1
        # watch out for <https://github.com/pre-commit/action/issues/169>
        with:
          extra_args: >
            --verbose
            --show-diff-on-failure
            --color=always
            --all-files
