name: pre-commit

# Controls when the workflow will run
on:
  push:
    paths:
       - '.github/workflows/pre-commit.yml'
       - '.pre-commit-config.yaml'
  pull_request:
    paths:
       - '.github/workflows/pre-commit.yml'
       - '.pre-commit-config.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v3
      - name: Lint the repository with pre-commit
        uses: pre-commit/action@v3.0.1
        # watch out for <https://github.com/pre-commit/action/issues/169>
        with:
          extra_args: --verbose
              #        run: |
              #          python3 -V
              #          pip3 install --upgrade pip
              #          pip3 install pre-commit==2.20.0
              #          pre-commit run --verbose
